denizen_scripts/survival/repo-link/items/system/.gitignore, denizen_scripts/survival/repo-link/items/system/combinations.py, denizen_scripts/survival/repo-link/items/system/soul_item_system.dsc
To assist in creating more soul types, I wrote a Python script that lists out every possible combination of soul types, that are not duplicates of each other. This is just my first PR on the matter. I will add more soul types later, in future PRs.
I have updated the NBT Attributes from their 1.15 form (camelCase) to their 1.16 form (snake_case). I have also corrected a minor spelling error on `netherite_sword`, as its slot was `mainahnd` and not `mainhand`.
commit bff7f0d88e3f744fb44502aee1b041d9ccf7aedf
Date:   Sun Jul 26 10:40:15 2020 -0400
Add Assassin soul.
commit b41a1cdc7ec48a32c656e90d556a309630a94cde
Date:   Sun Jul 26 10:36:12 2020 -0400 …
=> Initial PR for More Soul Types.

denizen_scripts/survival/repo-link/spawn_scripts/tutorial.dsc
Cleaned up the tutorial a bit, added punctuation and changed some sentence structure/colors.
=> Punctuation in tutorial.dsc

denizen_scripts/survival/repo-link/cuboid_creator.dsc, denizen_scripts/survival/repo-link/spawn_scripts/tutorial.dsc
=> Added interaction to the tutorial

denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_notifier.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/mod_main.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/tools/mod_report.dsc
This is the first command out of a total of 2.
I might need a channel webhook for the public Adriftus Discord server in the bug reports channel `#🐛bug-reports`
commit b836bbddb89d06d13004c8012eadb05a52030491
Date:   Wed Aug 19 00:32:09 2020 -0400
Add notify task.
commit 0a60b70bd655f09cd84de444ffe0213bd7fbe7dd
Date:   Wed Aug 19 00:31:34 2020 -0400
Start report command.
=> Issue 50 Pt. 1 - /report

denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_bans.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_commands.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_notifier.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_actions_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_ban_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_kick_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_send_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/tools/mod_report.dsc
This Pull Request consolidates the Adriftus Moderator Panel's notifier & message tasks. It involved combining similar functioning tasks together, and updating the passed definitions & task to run. This also meant removing the unnecessary tasks that were merged into other tasks.
**Consolidate notifier & message tasks.**
commit 978200ab4bb89ca4896e33d331b9280ea6216f62
Date:   Tue Sep 1 14:29:54 2020 -0400
Comment & spacing consistency updates.
commit f7e5fe54afbc1851892cddb21b7a5cdc39a0194e
Date:   Tue Sep 1 14:28:39 2020 -0400
Consolidate action notifier tasks.
commit 718f461c66acad792cd61c17f31e7d1f0d8714a9
Author: ChrispyMC …
=> Consolidate notifier & message tasks. -- Adriftus Moderator Panel

denizen_scripts/survival/repo-link/shops/market_system.dsc
This pull request fulfills the feature request outlined in [Issue #45](https://github.com/Adriftus-Studios/network-script-data/issues/45).
It adds netherite ingot (Min. $2200) & ancient debris (Min. $500).
**When you merge these changes, please mark Issue 45 as completed!**
**Feature Request -- Issue 45**
commit 973b7a94730a243382dda0aaebed93d603d17c2c
Date:   Tue Sep 1 17:49:33 2020 -0400
Clarify documentation.
commit 3bdc84b15e90e95ba2d732741987f3528100399e
Date:   Tue Sep 1 17:45:22 2020 -0400
Add ancient debris & netherite ingot.
=> Feature Request -- Issue 45

denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/functions/mod_message_discord.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/mod_infractions.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_ban_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_kick_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_online_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_send_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/tools/mod_gamemode.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/tools/mod_report.dsc
This pull request refactors the `:|:` (List split) data action to the `:->:` (List insert) data action. This refactoring applies to inventories, tasks, and procedures.
**Refactor :|: data action to :->:.**
commit 757a90e649127e2faa02060588ffd4648fdbebe1
Date:   Thu Sep 3 14:30:47 2020 -0400
Replace :|: data action with :->:.
=> Refactor :|: data action to :->:. -- Adriftus Moderator Panel

denizen_scripts/survival/repo-link/items/tiered_potions.dsc
Trying to fix the determine command.
**Uncancel the passive determine command.**
=> Determine command fix attempt. -- Tiered Potions

denizen_scripts/survival/repo-link/items/tiered_potions.dsc
This pull request reworks the `player consumes tiered_potion_*` event in accordance with Behr's suggestions.
**Rework `player consumes tiered_potion_*` event.**
=> Rework player consumes tiered_potion_* event. -- Tiered Potions

.gitignore, scriptdata/global/network/titles.yml
This pull request updates the titles configuration file. It removes a line from the [`.gitignore`](https://github.com/Adriftus-Studios/network-script-data/blob/master/.gitignore), and updates the `titles.yml` file.
Changes include:
- Removing offensive titles. (Slurs, insults, etc.)
- Removing irrelevant titles. (Servers, gamemodes, plugins, brands, etc.)
- Update some existing titles.
**Cleanup titles configuration file.**
commit 4fcf7e386b044ea12a64cec9e6dbc9ca0e9e03bb
Date:   Wed Sep 9 15:56:49 2020 -0400
Bigotry is not welcome in a school environment.
commit 4ea0560e9dc2bff251ee974a835461bf1e34f2fd
Date:   Wed Sep 9 15:53:42 2020 -0400
Remove titles from .gitignore.
[Kiyotaka …
=> Cleanup titles configuration file.

denizen_scripts/survival/repo-link/shops/specialty_shop.dsc
- Fixed procedural items
- Added quantity mechanics for buying and selling to the Specialty Shop
- Fixed Colours on buy and sell interactions
=> shop fixes

denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/mod_main.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_actions_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_ban_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_kick_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_online_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_panels_events.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_send_inv.dsc
This pull request converts the Adriftus Moderator Panel's inventories from using the `procedural items` key, to using a task to generate items and open the inventory. The logic mainly comes from [Xeane](https://discordapp.com/channels/626078288556851230/626080540638052382/754100392094072932) and [Behr's](https://discordapp.com/channels/626078288556851230/626080540638052382/754101987951509524) suggestions. I hope that the inventory events will still work, despite using modified inventories. It *should*, as using a task to generate and insert the items is pretty much functionally equivalent to using the `procedural items` inventory script container key.
**Convert from procedural items to tasks.**
commit 9a7bb21463345ca147ea17ed40828501b6860ba2
Author: …
=> Convert from procedural items to tasks. -- Adriftus Moderator Panel

denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/mod_main.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_actions_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_ban_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_kick_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_online_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/panels/mod_send_inv.dsc, denizen_scripts/hub1/repo-link/Adriftus_Moderator_Panel/tools/mod_spectate.dsc
This pull request fixes various issues in the Adriftus Moderator Panel.
1) Some online-only actions were usable on offline players. (Kick and Send)
2) Inventory titles were attached-player dependent. (`player.flag[...]`)
3) The To-Do list was outdated. Some items weren't checked off. (Organizational to-do items)
4) Command usage wasn't unified in system and did not represent what a moderator could do. (First argument wasn't required)
Another issue is that by default, LuckPerms does not allow permission lookups on offline players.
It seems like Denizen is looking up permissions on the main thread, rather than doing it asychronously. This would actually be the root cause of this problem.
The feature may not be supported, but the config option `vault-unsafe-lookups` *could* fix this if set …
=> Various Adriftus Moderator Panel fixes.

denizen_scripts/hub1/repo_link/Adriftus_Moderator_Panel/functions/mod_bans.dsc
This pull request fixes my ~~mortal sins~~ errors.
**Bad commit message.**
commit c538c7f1167fdbca08c9c1648f44c7266c63005d
Date:   Tue Sep 15 21:18:35 2020 -0400
Un-tern ID.
commit c60328596420394884ede15e83a40f879fab5a18
Date:   Tue Sep 15 21:14:54 2020 -0400
Missing ].
=> Xeane feedback. -- Adriftus Moderator Panel

denizen_scripts/hub1/repo_link/Elevator.dsc
A simple command that can be expanded upon later, for multiple uses.
=> Elevator.dsc

denizen_scripts/survival/repo_link/items/dragon_wings.dsc
This pull request resolves [Issue 114](https://github.com/Adriftus-Studios/network-script-data/issues/114). I have simply added `custom_model_data` under `mechanisms` and set it to `1`.
**Set CMD to 1.**
commit 0ac24d1e3c376f9f4ed0f8c3ab7c172002a23884 (HEAD -> kyu, origin/kyu, i-114)
Date:   Tue Sep 22 17:52:53 2020 -0400
Set CMD to 1.
=> Set CMD to 1. -- Issue 114

denizen_scripts/survival/repo_link/MobScripts/PhantomStuff.dsc
=> Phantom Fixes

denizen_scripts/global/server/commands/discord.dsc, denizen_scripts/survival/repo_link/spawn_scripts/player_joins_server.dsc, denizen_scripts/survival/repo_link/systems/random_text_announcer.dsc, denizen_scripts/survival/repo_link/temporary/player_join_messages.dsc
Removed server "alpha" message
Fixed /discord text gore in chat
Created random announcer to inform players of events every 30 minutes
Created login time flag for tracking current play session length
=> Multiple text fixes and additions

denizen_scripts/survival/repo_link/Commands/drown.dsc, denizen_scripts/survival/repo_link/MobScripts/HuskStuff.dsc, denizen_scripts/survival/repo_link/combat_log.dsc, denizen_scripts/survival/repo_link/global_systems/economy_test.dsc, denizen_scripts/survival/repo_link/spawn_scripts/player_joins_server.dsc, denizen_scripts/survival/repo_link/systems/random_text_announcer.dsc
=> Nightly 10 25 20

denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc, denizen_scripts/survival/repo_link/global_systems/economy_test.dsc, denizen_scripts/survival/repo_link/shops/market_system.dsc, denizen_scripts/survival/repo_link/systems/SilkSpawner.dsc, denizen_scripts/survival/repo_link/systems/random_text_announcer.dsc
Fixed hopper protection and added birch blocks to market system
added farmland protection.
attempted fix of /pay
stole behrcrafts silk touch spawner script
=> Nightly 10 28 20

denizen_scripts/survival/repo_link/items/backpack.dsc
putting a bandaid on the stab wound
=> attempting to fix backpack

denizen_scripts/survival/repo_link/global_systems/economy_test.dsc, denizen_scripts/survival/repo_link/items/grappling_hook.dsc
correcting waitlimit to resolve https://github.com/Adriftus-Studios/network-script-data/issues/180
=> Nightly 10/28/20

denizen_scripts/relay/repo_link/commands/restart.dsc
* Add two manager roles to command as you indicated they are administration for the servers
* Add help msic argument
* Add response for using command wrongly
=> Add handles for invalid usage and a help window

denizen_scripts/survival/repo_link/global_systems/warps.dsc, denizen_scripts/survival/repo_link/systems/server_restarter.dsc
Attempted to make an automated server restarter for survival.
Corrected invalid material name in warps.dsc
=> nightly-10_29_20

denizen_scripts/survival/repo_link/systems/SilkSpawner.dsc
=> Fix Silk Touch Spawners

denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc, denizen_scripts/survival/repo_link/items/backpack.dsc
added a bunch of block protections, added nether warts to farmable blocks
=> Nightly 11 1 20
